### ISSUE TITLE
Capture.ColorImage transform  System.Drawing.Bitmap

### ISSUE THREAD

**Issue by YJ-L-2017** [bibigone/k4a.net#42]
当camera 设置为时ColorFormat = ImageFormat.ColorMjpg,;时，Capture.ColorImage 如何转换为System.Drawing.Bitmap

**Comment by baSSiLL** [comment]
Motion JPEG frames are regular JPEG images which may lack some data in the header. You just need to wrap a frame data into a `Stream` object and use the `Bitmap` constructor which takes a `Stream` argument. It will load the frame to a `Bitmap` as a JPEG image.
If you can use the unsafe code then the easiest way is to use the `UnmanagedMemoryStream`.
```cs
byte* ptr = (byte*)capture.ColorImage.Buffer.ToPointer();
Bitmap bitmap;
using (var stream = new UnmanagedMemoryStream(ptr, capture.ColorImage.SizeBytes))
{
    bitmap = new Bitmap(stream);
}
```
Otherwise, you can copy data to a byte array and wrap it to a `MemoryStream`.
```cs
var copy = new byte[capture.ColorImage.SizeBytes];
// or use ArrayPool to prevent excess allocations if it's available on your target .NET
//var copy = ArrayPool<byte>.Shared.Rent(capture.ColorImage.SizeBytes);
Marshal.Copy(capture.ColorImage.Buffer, copy, 0, copy.Length);
Bitmap bitmap;
using (var stream = new MemoryStream(copy))
{
    bitmap = new Bitmap(stream);
}
// don't forget to return the array to the pool if using that
//ArrayPool<byte>.Shared.Return(copy);
```
